CREATE TABLE IF NOT EXISTS usuarios (
  id_usuario BIGINT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(120) NOT NULL,
  cpf CHAR(11) NOT NULL,
  email VARCHAR(160) NOT NULL,
  senha VARCHAR(100) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  grupo VARCHAR(20) NOT NULL,
  data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
  CONSTRAINT uq_usuarios_cpf UNIQUE (cpf),
  CONSTRAINT uq_usuarios_email UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
